### ISSUE TITLE
Link other oauth account

### ISSUE THREAD

**Issue by Its-Alex** [Its-Alex/HyperTube#22]
Need to link others oauth account (in profile) there are links here :
42 = http://localhost:3005/auth/42?token=[token]
github = http://localhost:3005/auth/github?token=[token]
facebook = http://localhost:3005/auth/facebook?token=[token]

Need to use
```javascript
window.location.href
```

**Comment by vacrozet** [comment]
l'authentification avec git hub ne marche pas .... ça me revoit une erreur ligne 56 en back le fichier oauth.js

**Comment by Its-Alex** [comment]
C'est quoi l'URL sur laquelle tu envoies ?

**Comment by Its-Alex** [comment]
Aucune erreur, tu peux reproduire l'erreur stp, poste la aussi dans le commentaire en markdown JS

**Comment by vacrozet** [comment]
TypeError: Cannot read property '0' of undefined
    at model.getUserByOauth.then.res (/Users/vacrozet/Desktop/HyperTube/app/controllers/user/oauth.js:56:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
