### ISSUE TITLE
Need data from movie in player

### ISSUE THREAD

**Issue by Its-Alex** [Its-Alex/HyperTube#30]

**Comment by vacrozet** [comment]
Tu veux que je te balance le tab du film que je recoi de tmdb dans le le fichier play ?

**Comment by Its-Alex** [comment]
Oui

**Comment by vacrozet** [comment]
si je te le met dans le store c'est bon ?

**Comment by Its-Alex** [comment]
Comme tu veux mais prévois si le mec va sur le lien directe sans passer par le site

**Comment by vacrozet** [comment]
ca veut dire que je suis obliger de faire une requette, je peux pas le passer en localStorage. Et puis si je le passe dans le store et que le mec ctrl + R je suis dans la merde.

**Comment by Its-Alex** [comment]
Fais une requête alors, sinon il y a des check genre "j'ai les datas ? Cool : je fais la requete"

**Comment by vacrozet** [comment]
oui mais les datas tu veux que je les envoi comment ? tu veux que je mette un tab direct dans le lien ? ca marche pas je pense

**Comment by Its-Alex** [comment]
Débrouille toi.
