### ISSUE TITLE
On respecte pas le sujets...

### ISSUE THREAD

**Issue by Its-Alex** [Its-Alex/HyperTube#47]
Extrait du sujet : "Cette section devra présenter le détail d’une vidéo, c’est à dire afficher le player de la
vidéo ainsi que - si disponible - le résumé, le casting (au moins producteur, réalisateur,
acteurs principaux, etc...), l’année de production, la durée, la note IMDb, une image de
couverture et tout ce qui vous semblerait pertinent."
Ce sera pas avec le player mais faut que vous rajoutiez le casting/année de prod/durée, toutes ces infos sont envoyé par tmdb

**Comment by vacrozet** [comment]
j'ai la durée, l'année de sortie  et non l'année de production et non plus le casting...

**Comment by Its-Alex** [comment]
Tu peux recuperer le casting avec tmdb, l'annee de sortie c'est bon, si tu cherches tu auras l'annee de production aussi et... https://developers.themoviedb.org/3/movies/get-movie-credits quand je te dis que tu cherche pas c'est ouf

**Comment by vacrozet** [comment]
ah putin en plus je suis aller sur cette page et je me suis dis que c'etait ça vue ce que ca retournais.

**Comment by Its-Alex** [comment]
Bah bravo, sinon pour l'année de prod tant pis

**Comment by Its-Alex** [comment]
#56
