### ISSUE TITLE
inscription/connexion

### ISSUE THREAD

**Issue by rim31** [Its-Alex/HyperTube#48]
j'avais des pb de profil corrompu ou profil pourri. j'ai vidé le localhost storage mais

- en mode privee, ou quand je suis connecté et je suissur Profil,  j'ai  ce texte qui s'affiche quand je me connecte avec github :
 TypeError: Cannot read property 'length' of undefined
    at model.getUserByOauth.then.res (/Users/oseng/Desktop/Rendu/leshomos/app/controllers/user/oauth.js:56:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

- connexion avec api42 ok

- inscription par mail, j'ai rien reçu comme mail9j'ai mis une adresse jetable yopmail)

**Comment by Its-Alex** [comment]
Normal pour le mail on en envoie pas pour l'inscription

**Comment by Its-Alex** [comment]
C'est avec quel oauth que tu as eu ce probleme ? Github / Facebook ?

**Comment by rim31** [comment]
github

**Comment by Its-Alex** [comment]
Ton github renvoie aucune information

**Comment by Its-Alex** [comment]
Bref c'est patch normalement

**Comment by Its-Alex** [comment]
Ton facebook marche ? @rim31

**Comment by rim31** [comment]
marche pas . vient de tester FB en mode private

{"success":false,"err":"Internal server error"}

**Comment by Its-Alex** [comment]
T'as tout mis en private et tu as pas accepter de nous donner ton profile, bref c'est patch dans la prochaine PR

**Comment by Its-Alex** [comment]
#55
