### ISSUE TITLE
Click double request

### ISSUE THREAD

**Issue by Its-Alex** [Its-Alex/HyperTube#54]
Quand on clic sur une qualite ca envoie deux requetes

**Comment by Its-Alex** [comment]
@vacrozet C'est celle la la prochaine issu sur laquelle tu bosse stp

**Comment by vacrozet** [comment]
tu l'as vue ?

**Comment by Its-Alex** [comment]
Le probleme oui

**Comment by Its-Alex** [comment]
Ou en tout cas faut l'empecher avec un debounce

**Comment by vacrozet** [comment]
=D

**Comment by vacrozet** [comment]
c'est ok
