### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by sagar1garg** [Its-Alex/HyperTube#73]
How do I get past the login screen in the dev env? I launched it on my windows machine to test

**Comment by wickedpool** [comment]
Hi,

You'll need a .config.json file with all API keys, we didn't commit this
file cause it's a private one.

**Comment by sagar1garg** [comment]
can u provide a sample?

**Comment by Its-Alex** [comment]
Are you from 42 ? I will add a sample to readme later today :)

**Comment by sagar1garg** [comment]
No

**Comment by Its-Alex** [comment]
Solve in https://github.com/Its-Alex/HyperTube/commit/795ffeca7b370d6d6b1e53c8bee69e4b8e03c275

For your problem you will need to find model database, put it in database and create an user
